steps:
- name: 'gcr.io/cloud-builders/docker'
  entrypoint: bash
  args:
  - -c
  - |
    python --version
    pip install -r requirements.txt
    python setup.py install
images:
- 'gcr.io/dinoai-430611/my-app'
