steps:
  - name: gcr.io/cloud-builders/gcloud
    args:
      - '-c'
      - |
        gcloud config set project dinoai-430611
        gcloud app deploy app.yaml --quiet
    entrypoint: bash
timeout: 1200s
logsBucket: 'gs://dinoaibucket'
options:
  machineType: E2_HIGHCPU_8
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
