# Python 3.10.8 tabanlı bir imaj kullanıyoruz
FROM python:3.10.8

# Çalışma dizinini ayarlıyoruz
WORKDIR /app

# Gereksinim dosyasını kopyalıyoruz
COPY requirements.txt requirements.txt

# Gereksinimleri yüklüyoruz
RUN pip install -r requirements.txt

# Uygulama dosyalarını kopyalıyoruz
COPY . .

# Uygulamanın çalıştırılacağı portu belirliyoruz
EXPOSE 8080

# Uygulamayı başlatıyoruz
CMD ["gunicorn", "-b", ":8080", "main:app"]
